services:
  glue:
    image: public.ecr.aws/glue/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue-local
    volumes:
      - ./src:/home/hadoop/workspace/src
      - ./tests:/home/hadoop/workspace/tests
      - ./test_data:/home/hadoop/workspace/test_data
      - ./dist:/home/hadoop/workspace/dist
      - ~/.aws:/home/hadoop/.aws:ro
      - ./pytest.ini:/home/hadoop/workspace/pytest.ini
      - ./pyproject.toml:/home/hadoop/workspace/pyproject.toml
      - ./log4j-local.properties:/home/hadoop/workspace/log4j-local.properties
    environment:
      - DISABLE_SSL=true
      - ENVIRONMENT=local
      - PYTHONPATH=/home/hadoop/workspace/src
      - PYTEST_INTEGRATION=1
    working_dir: /home/hadoop/workspace
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo 'AWS Glue 4.0 container ready for testing' && tail -f /dev/null"]
    stdin_open: true
    tty: true
    ports:
      - "4040:4040"  # Spark UI
      - "8080:8080"  # Glue Dev Endpoint UI
    networks:
      - glue-network

networks:
  glue-network:
    driver: bridge
