services:
  glue:
    image: public.ecr.aws/glue/aws-glue-libs:5
    container_name: glue-local
    volumes:
      - ./src:/home/hadoop/workspace/src
      - ./tests:/home/hadoop/workspace/tests
      - ./tests/test_data:/home/hadoop/workspace/data
      - ~/.aws:/home/hadoop/.aws:ro
      - ../dist:/home/hadoop/workspace/dist
      - ./requirements.txt:/home/hadoop/workspace/requirements.txt
      - ./log4j-local.properties:/home/hadoop/workspace/log4j-local.properties
    environment:
      - DISABLE_SSL=true
      - ENVIRONMENT=local
      - PYTHONPATH=/home/hadoop/workspace/src
      - PYTEST_INTEGRATION=1
    working_dir: /home/hadoop/workspace
    entrypoint: ["/bin/sh", "-c"]
    command: ["pip install --user -r /home/hadoop/workspace/requirements.txt && echo 'Dependencies installed successfully' && tail -f /dev/null"]
    stdin_open: true
    tty: true
    ports:
      - "4040:4040"  # Spark UI
      - "8080:8080"  # Glue Dev Endpoint UI
    networks:
      - glue-network

networks:
  glue-network:
    driver: bridge
