version: '3.8'

services:
  glue:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    container_name: glue-local
    volumes:
      - ./src:/home/glue_user/workspace/src
      - ./tests:/home/glue_user/workspace/tests
      - ./tests/test_data:/home/glue_user/workspace/data
      - ~/.aws:/home/glue_user/.aws:ro
      - ../dist:/home/glue_user/workspace/dist
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - DISABLE_SSL=true
      - ENVIRONMENT=local
      - PYTHONPATH=/home/glue_user/workspace/src
    working_dir: /home/glue_user/workspace
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "4040:4040"  # Spark UI
      - "8080:8080"  # Glue Dev Endpoint UI
    networks:
      - glue-network

  # Optional: LocalStack for AWS service emulation (if needed for integration tests)
  # localstack:
  #   image: localstack/localstack:2.3
  #   container_name: localstack
  #   environment:
  #     - SERVICES=s3,secretsmanager,sqs,sns
  #     - DEBUG=1
  #     - DATA_DIR=/tmp/localstack/data
  #     - PERSISTENCE=1
  #   ports:
  #     - "4566:4566"
  #   volumes:
  #     - localstack_data:/tmp/localstack
  #   networks:
  #     - glue-network

networks:
  glue-network:
    driver: bridge

volumes:
  localstack_data: