name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive infrastructure/
      
      - name: Terraform Validate
        run: |
          for env in dev staging prod; do
            cd infrastructure/environments/$env
            terraform init -backend=false
            terraform validate
            cd -
          done

  test-glue-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: cd glue-jobs && poetry install
      
      - name: Run linter
        run: |
          cd glue-jobs
          poetry run ruff check .
          poetry run black --check .
      
      - name: Run type checker
        run: cd glue-jobs && poetry run mypy src/
      
      - name: Run unit tests
        run: cd glue-jobs && poetry run pytest tests/unit -v --cov=src --cov-report=term-missing
      
      - name: Build package
        run: |
          cd glue-jobs
          poetry build
          cd src && zip -r ../../dist/utils.zip utils transformations validators