name: Release Glue Jobs

on:
  push:
    branches:
      - main
    paths:
      - 'glue-jobs/**'
  workflow_dispatch:

concurrency:
  group: release-glue-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Run Glue Jobs Tests Before Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Test glue-jobs
      - name: Install glue-jobs dependencies
        run: cd glue-jobs && uv sync --group dev

      - name: Run glue-jobs linter
        run: |
          cd glue-jobs
          uv run ruff check .
          uv run ruff format --check .

      - name: Run glue-jobs type checker
        run: cd glue-jobs && uv run ty src/

      - name: Run glue-jobs unit tests
        run: cd glue-jobs && uv run pytest -m unit -v --cov=src --cov-report=term-missing

  build:
    name: Build Glue Jobs Package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build glue-jobs package
        run: make package-jobs

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: glue-build-artifacts
          path: dist/
          retention-days: 30

  release:
    name: Python Semantic Release for Glue Jobs
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      id-token: write
    outputs:
      version: ${{ steps.release.outputs.version }}
      released: ${{ steps.release.outputs.released }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: cd glue-jobs && uv sync --group dev

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: glue-build-artifacts
          path: dist/

      - name: Action | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          directory: "./glue-jobs"

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v10.3.1
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
          directory: "./glue-jobs"

      - name: Upload | Distribution Artifacts
        uses: actions/upload-artifact@v4
        if: steps.release.outputs.released == 'true'
        with:
          name: glue-distribution-artifacts
          path: dist
          if-no-files-found: error

  notify-success:
    name: Notify Glue Jobs Release Success
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.released == 'true'
    steps:
      - name: Release Success Notification
        run: |
          echo "🎉 Glue Jobs release ${{ needs.release.outputs.version }} completed successfully!"
          echo "📦 New version has been published to GitHub Release"
          echo "📋 Changelog has been updated"
          echo "🏷️ Git tag has been created"
          echo "📁 Distribution artifacts uploaded"

  notify-no-release:
    name: Notify No Glue Jobs Release Needed
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.released == 'false'
    steps:
      - name: No Release Notification
        run: |
          echo "ℹ️ No glue jobs release needed"
          echo "📝 No conventional commits found in glue-jobs/ that trigger a release"
          echo "💡 Use feat:, fix:, or breaking changes to trigger releases"

  notify-failure:
    name: Notify Glue Jobs Release Failure
    needs: [test, build, release]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Release Failure Notification
        run: |
          echo "❌ Glue Jobs release failed!"
          echo "🔍 Please check the workflow logs for details"
          echo "🛠️ Fix any issues and push again to retry"